# Generated by Django 6.0.3 on 2026-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_lesson_options_course_price_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1500,
                help_text="Укажите цену курса",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
