# Generated by Django 6.0.3 on 2026-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор цены в Stripe",
                max_length=1000,
                null=True,
                verbose_name="ID цены Stripe",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор продукта в Stripe",
                max_length=1000,
                null=True,
                verbose_name="ID продукта Stripe",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор сессии оплаты в Stripe",
                max_length=1000,
                null=True,
                verbose_name="ID сессии Stripe",
            ),
        ),
    ]
