# Generated by Django 6.0.3 on 2026-03-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0006_alter_payment_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на страницу оплаты в Stripe",
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
