# Generated by Django 6.0.2 on 2026-03-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0007_alter_payment_payment_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата последнего обновления курса",
                verbose_name="Дата обновления",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата последнего обновления урока",
                verbose_name="Дата обновления",
            ),
        ),
    ]
